course = (
    "AB-ENGLISH",
    "AB-LITERATURE",
    "AB-POLSCI",
    "AB-PSYCH",
    "BEED",
    "BPeA",
    "BPED",
    "BSA",
    "BSBA",
    "BSCA",
    "BSCE",
    "BSCPE",
    "BSCRIM",
    "BSCS",
    "BSECE",
    "BSED",
    "BSEE",
    "BSHM",
    "BSIE",
    "BSIT",
    "BSMA",
    "BSME",
    "BSNED",
    "BSOA",
    "BSREM",
    "BSSW",
)

positions = (
    "Trainee Writer",
    "Trainee Cartoonist",
    "Trainee Layout Artist",
    "Trainee Photojournalist",
    "Junior Staff Writer",
    "Junior Staff Cartoonist",
    "Junior Staff Layout Artist",
    "Junior Staff Photojournalist",
    "Senior Staff Writer",
    "Senior Staff Cartoonist",
    "Senior Staff Layout Artist",
    "Senior Staff Photojournalist",
    "Art Editor",
    "Photo Editor",
    "Graphics Editor",
    "Online Editor",
    "Feature Editor",
    "News Editor",
    "Ethics and Legal Standards Editor",
    "Finance Manager",
    "Creative Director",
    "Planning and Research Director",
    "Managing Director",
    "Associate Editor",
    "Editor in Chief"
)


default_password = "lakandiwa@2023"


exempted = (
    "Incumbent Lakandiwa Members",
    "Working Scholars(AWS and ACG)",
    "Athletes",
    "Drum and Bugle and Lyrists Corps (DBLC)",
    "Nuns",
    "Cross enrollees",
    "Teaching personnel",
    "OJT Students",
    "Postgraduate students",
    "(Cultural) Symphonic Orchestra",
    "(Cultural) Chorus",
    "(Cultural) Theater Workshop Company",
    "(Cultural) UC Cheerleading Team",
    "(Cultural) UC Dance Company",
    "(Cultural) Campus Ministry",
    "University academic scholars (UCASS and UCS3)",
    "SBO presidents",
    "Ex-trainees",
    "Reviewees of any board examination"
)

